# Generated by Django 5.2.3 on 2025-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
