# Generated by Django 5.2.3 on 2025-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credential_email_credential_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
