# Generated by Django 5.2.3 on 2025-08-10 12:22

import credentials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_credential_site_url_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[credentials.validators.validate_phone_number]),
        ),
    ]
