# Generated by Django 5.2.3 on 2025-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_alter_credential_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='category',
        ),
        migrations.AddField(
            model_name='credential',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='credentials', to='credentials.category'),
        ),
    ]
