# Generated by Django 5.2.3 on 2025-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_remove_credential_category_credential_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
